[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
rayon = "1.11.0"
